// <auto-generated />
using System;
using ExcelImporter.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ExcelImporter.Repository.Migrations
{
    [DbContext(typeof(ExcelImporterDbContext))]
    partial class ExcelImporterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcelImporter.Repository.Entities.CardImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCurrency")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ACCOUNT_CURRENCY");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ACTIVATION_DATE");

                    b.Property<decimal?>("ArrestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("ARRESTED_AMOUNT");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BIRTHDAY");

                    b.Property<string>("CardBranch")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CARD_BRANCH");

                    b.Property<string>("CardProductName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CARD_PRODUCT_NAME");

                    b.Property<string>("CardType")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CARD_TYPE");

                    b.Property<string>("ClerkCode")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CLERK_CODE");

                    b.Property<string>("ClientBranch")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CLIENT_BRANCH");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CLIENT_ID");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CLOSING_DATE");

                    b.Property<string>("ContactAddress")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CONTACT_ADDRESS");

                    b.Property<string>("Contactless")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CONTACTLESS");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CONTRACT_NUMBER");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATION_DATE");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("CREDIT_LIMIT");

                    b.Property<decimal?>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("CURRENT_BALANCE");

                    b.Property<string>("CurrentCmsStatus")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CURRENT_CMS_STATUS");

                    b.Property<string>("CurrentOnlineStatus")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CURRENT_ONLINE_STATUS");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CUSTOMER_NAME");

                    b.Property<string>("EmbossingName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMBOSSING_NAME");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRY_DATE");

                    b.Property<string>("ExternalAcc")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EXTERNAL_ACC");

                    b.Property<string>("ExternalCode")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EXTERNAL_CODE");

                    b.Property<string>("FinancialProfile")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("FINANCIAL_PROFILE");

                    b.Property<string>("Gender")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("GENDER");

                    b.Property<string>("InternalAcc")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("INTERNAL_ACC");

                    b.Property<string>("IssuancePriority")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ISSUANCE_PRIORITY");

                    b.Property<string>("IssuanceReason")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ISSUANCE_REASON");

                    b.Property<string>("LimitCurrency")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("LIMIT_CURRENCY");

                    b.Property<string>("LimitGroup")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("LIMIT_GROUP");

                    b.Property<string>("Mbr")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("MBR");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("MOBILE_NUMBER");

                    b.Property<decimal?>("OnHold")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("ON_HOLD");

                    b.Property<string>("Pan")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("PAN");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("PASSPORT_NUMBER");

                    b.Property<string>("PersonalCode")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("PERSONAL_CODE");

                    b.HasKey("Id");

                    b.ToTable("CARD_IMPORTS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
